spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

aws:
  s3:
    bucket: ${AWS_S3_BUCKET:team7-whiskeynote-images}

oauth:
  google:
    client-id: ${OAUTH_GOOGLE_CLIENT_ID:}
    client-secret: ${OAUTH_GOOGLE_CLIENT_SECRET:}
    redirect-uri: ${OAUTH_GOOGLE_REDIRECT_URI:}
  kakao:
    client-id: ${OAUTH_KAKAO_CLIENT_ID:}
    client-secret: ${OAUTH_KAKAO_CLIENT_SECRET:}
    redirect-uri: ${OAUTH_KAKAO_REDIRECT_URI:}
  naver:
    client-id: ${OAUTH_NAVER_CLIENT_ID:}
    client-secret: ${OAUTH_NAVER_CLIENT_SECRET:}
    redirect-uri: ${OAUTH_NAVER_REDIRECT_URI:}
